[package]
name = "tea-bond"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tea-time = "0.4"
chrono = "0.4"
anyhow = "1"
