[workspace]
members = [
    "tea-bond",
    "tea-calendar",
    "pybond", 
]

default-members = [
    "tea-bond",
    "tea-calendar",
    # "pybond",
]


resolver = "2"

[workspace.dependencies]
chrono = "0.4"
tea-calendar = { path = "tea-calendar" }