[package]
name = "pybond"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pybond"
crate-type = ["cdylib"]

[features]
default = ["download"]
numpy = ["dep:numpy", "tevec/ndarray"]
download = ["tea-bond/download"]

[dependencies]
pyo3 = { version = "0.23", features = [
    "chrono",
    "extension-module",
    "abi3-py38",
    "anyhow",
    # "experimental-inspect",
    "multiple-pymethods",
] }
#tea-bond = { git = "https://github.com/teamon9161/tea-bond.git", branch = "master" }
tea-bond = { path = ".." }
chrono = { version = "0.4", default-features = false }
numpy = { version = "0.23", optional = true }
tevec = { version = "0.5.0", optional = true }
parking_lot = "0.12"
# ndarray = { version = "0.16", optional = true }
